name: Upstream Sync

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动执行
  workflow_dispatch:   # 允许手动点击

# 全局开启 Node.js 24 环境变量，彻底消除弃用警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Sync upstream changes
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/bingoguo93/OpenWRT-CI-XG-040G-MD.git"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
